# list_cache_files.yml
name: List Cache Files

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  list-files:
    runs-on: ubuntu-latest
    env:
      DATA_CACHE_DIR: data

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Download data catalog artifact
        uses: actions/download-artifact@v4
        with:
          name: data-catalog
          path: ${{ env.DATA_CACHE_DIR }}

      - name: Run list files script
        env:
          DATA_CACHE_DIR: ${{ env.DATA_CACHE_DIR }}
        run: python scripts/list_files.py

